spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://121.36.209.225:3306/vblog?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  redis:
    port: 6379
    host: 121.36.209.225
    database: 0
    timeout: 5000


  # 设置全局日期格式,如果设置这个格式,则代码中@DateTimeFormat(pattern = "dd/MM/yyyy") 无效!!
  mvc:
    format:
      date: yyyy-MM-dd HH:mm:ss

  jackson:
    time-zone: GMT+8

server:
  servlet:
    encoding:
      charset: utf-8
  port: 8989


# Mybatis 配置
mybatis:
  type-aliases-package: com\example\vblogservice\entity\domian
  mapper-locations: classpath:/mybatis/mapper/*.xml

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true

#logging:
#  logback:
#    rollingpolicy:
#      file-name-pattern: ${Date} + mps.log
#  file:
#    path: ./log/


